# Generated by Django 3.1.7 on 2021-03-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated At')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('nome_categoria', models.CharField(max_length=50, verbose_name='Categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
